config/routes.rb
Rails.application.routes.draw do
  devise_for :users, :controllers => {registrations: 'registrations'}
  root 'folders#index'

  get 'folders/parent/:parent_id/new', to: 'folders#new', as: 'new_folder'

  resources 'folders', except: [:index, :new] do
  	resources 'uploads', only: [:index, :new, :create, :destroy]
  end

  get 'shared', to: 'shares#index'


  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/folder.rb
class Folder < ApplicationRecord

	has_one :share
	belongs_to :user, foreign_key: "owner_id", class_name: "User"

	
	acts_as_tree

	validates :name, presence: true, uniqueness: {case_sensitive: false, scope: :owner_id}
	
	has_many_attached :uploads

end

app/models/share.rb
class Share < ApplicationRecord

	self.table_name = "shares"

	validates :user_id, uniqueness: {scope: :folder_id}

	belongs_to :user
	belongs_to :folder

end

app/models/upload.rb
class Upload < ApplicationRecord

	self.table_name = "folders"

end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable

  has_many :folders, foreign_key: "owner_id"

  has_many :shares
  has_many :shared_folders, through: :shares, source: :folder
  # the ones that are shared with current user
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
	before_action :authenticate_user!

end

app/controllers/folders_controller.rb
class FoldersController < ApplicationController

	layout 'dropbox'

	before_action :get_folder, only: [:show, :update, :destroy]
	before_action :get_root_folder, only: [:index, :create, :destroy, :update]
	before_action :get_folders, only: [:index]

	def index
	end

	def new
		@folder = Folder.new
		@parent_id = params[:parent_id] if params[:parent_id]
	end

	def create
		@folder = Folder.new(folder_params)
		@folder.owner_id = current_user.id

		@folder.parent_id = get_parent_param['parent_id']
		@folder.parent_id = @root_folder.id if @folder.parent_id.nil?
		
		@folder.save
	end

	def show
	end

	def update
		@folder.update(folder_params)
		get_folder
		# redirect_to root_path
	end

	def destroy
		if @folder.present?
			@folder.destroy
		end
	end

	# might be used in other classes as well
	private
	def get_root_folder
		@root_folder = current_user.folders.first_or_create("name": "root")
	end

	def folder_params
		params.require(:folder).permit(:name, :folder_description)
	end

	def get_parent_param
		params.require(:folder).permit(:parent_id)
	end

	def get_folder
		@folder = Folder.find(params[:id])
	end

	def get_folders
		@folders = @root_folder.children
	end

end

app/controllers/registrations_controller.rb
class RegistrationsController < Devise::RegistrationsController

  private
  def account_update_params
    params.require(:user).permit(:name, :email, :password, :password_confirmation, :current_password)
  end
end

app/controllers/shares_controller.rb
class SharesController < ApplicationController

	layout 'dropbox'

	def index
		@folders = current_user.shared_folders
	end

end

app/controllers/uploads_controller.rb
class UploadsController < ApplicationController


	layout 'dropbox'

	
	before_action :get_folder, :get_root_folder, :get_folders, :has_permission?
	before_action :is_owner?, except: [:index]

	def index
		render file: 'folders/index'
	end

	def new
		@uploads = @folder.uploads
	end

	def create
		@folder.update(uploads_params)
	end

	def destroy
		@folder.uploads.delete(params[:id])
	end


	private

	def uploads_params
		params.require(:upload).permit(uploads: [])
	end
	
	def get_folder
		@folder = Folder.find(params[:folder_id])
	end

	def get_root_folder
		@root_folder = @folder
	end

	def get_folders
		@folders = @root_folder.children
	end

	def has_permission?
		redirect_to root_path if (!is_shared? && (@root_folder.owner_id != current_user.id))
	end

	def is_owner?
		redirect_to root_path if @folder.owner_id != current_user.id
	end

	def is_shared?

		flag = false
		folder = @root_folder
		
		while folder.parent.present?
			result = current_user.shares.find_by('folder_id': folder.id)

			if result
				flag = true
				break
			end
			folder = folder.parent
		end

		flag
	end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/folders/_each.html.erb
<div class="text-center pl-5 folder row mb-4" >
	<div class="zoom">
		<%= link_to folder_uploads_path(folder) do %>
		<i class="fas fa-folder xl-icon mb-2" title="<%= folder.name %>"></i>
		<% end %>
		<br>
		<div>
			<%= folder.name %>
		</div>
	</div>
	<div class="col-md-6">
		<% if @root_folder.owner_id == current_user.id %>
		
		<%= link_to folder_path(folder), remote: true, data: {confirm: 'Do you want to remove the folder?'} do %>
		<i class="zoom fas fa-share-alt xs-icon pr-2 float-left share" title="<%= folder.name %>" data-toggle="modal" data-target="#share_modal"></i>
		<% end %>

		<%= link_to folder_path(folder), remote: true do %>
		<i class="zoom fas fa-pencil-alt xs-icon float-left edit pr-2" title="<%= folder.name %>" data-toggle="modal" data-target="#add_folder_modal"></i>
		<% end %>

		<%= link_to folder_path(folder), remote: true, data: {confirm: 'Do you want to remove the folder?'}, method: :delete do %>
		<i class="zoom fas fa-trash-alt xs-icon pr-2 float-left delete" title="<%= folder.name %>"></i>
		<% end %>


		<% end %>
	</div>
</div>

app/views/folders/_form.html.erb
<%= simple_form_for @folder, remote: true, id: 'folder_form' do |f| %>
<div class="modal-content">
	<div class="modal-header">
		<h5 class="modal-title" id="exampleModalLabel">
			<%= @folder.new_record? ? "Create " : "Edit " %>Folder
		</h5>
		<button type="button" class="close" data-dismiss="modal" aria-label="Close" id="close_form_modal">
			<span aria-hidden="true">&times;</span>
		</button>
	</div>
	<div class="modal-body">
		<div class="form-group">
			<%= f.input :name, placeholder: "Enter Folder Name.", class: "form-control", required: "required" %>
		</div>
		<%= f.input :parent_id, as: 'hidden', input_html: { value: @parent_id} %>
		<div class="form-group">
			<%= f.label :folder_description %>
			<%= f.text_area :folder_description, placeholder: "Enter Folder Description.", class: "form-control" %>
		</div>
	</div>
	<div class="modal-footer">
		<button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal">Close</button>
		<button type="submit" class="btn btn-sm btn-primary">Save changes</button>
	</div>
</div>
<% end %>

app/views/folders/_list.html.erb
<% if @folders.present? %>
<div class="text-info col-md-12 m-2">
	<h5>Folders</h5>
</div>

<% @folders.each do |folder| %>
<div id="folder_<%= folder.id %>">
	<%= render 'folders/each', {folder: folder} %>
</div>
<% end %>

<% end %>

app/views/folders/create.js.erb
$("#close_form_modal").trigger("click");
$("#folder_list").append("<%= j render 'folders/each', {folder: @folder} %>");

app/views/folders/destroy.js.erb
$("#folder_<%= @folder.id %>").html("");

app/views/folders/index.html.erb
<!-- links for new -->
	<%= render "shared/create_buttons" %>
<!-- links for new -->



<%= render "shared/modals" %>


<div class="clearfix mt-2">
</div>

<!-- list begins -->
<div class="row" id="folder_list">
	<%= render 'folders/list' %>
</div>
<!-- list end -->


<div class="row" id="upload_list">
	<%= render 'uploads/list' %>
</div>

app/views/folders/new.js.erb
$("#folder_form_render").html("<%= j render 'folders/form' %>");

app/views/folders/old_update.js.erb
$("#close_form_modal").trigger("click");
$("#folder_<%= @folder.id %>").html("<%= j render 'folders/each', {folder: @folder} %>");

app/views/folders/show.js.erb
$("#folder_form_render").html("<%= j render 'folders/form' %>");

app/views/folders/update.js.erb
$("#close_form_modal").trigger("click");
$("#folder_<%= @folder.id %>").html("<%= j render 'folders/each', {folder: @folder} %>");

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DropboxClone</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>

<script src="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.js"></script>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/jquery-modal/0.9.1/jquery.modal.min.css" />
</head>

<body>
  <%= render "shared/navbar" %>

  <div class="container col-md-10 p-2 mt-2">
    <%= render "shared/flash_messages" %>
    <div class="mt-1 row">
      <%= yield %>
    </div>
  </div>

</body>
</html>

app/views/layouts/dropbox.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>DropboxClone</title>
  <%= csrf_meta_tags %>
  <%= csp_meta_tag %>

  <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <%= render "shared/navbar" %>

  <div class="container col-md-11 p-2 pl-4 pr-4 mt-2 border border-secondary rounded bg-snow">
    <%= render "shared/flash_messages" %>
    <%= yield %>
  </div>

</body>
</html>

app/views/shared/_create_buttons.html.erb
<% if @root_folder.owner_id != current_user.id %>
<div>
	<span class="text-info"><strong>Shared by: </strong><%= @root_folder.user.name %></span>
</div>
<% end %>

<div>
	<div class="float-left">

		<% nav_list = [] %>
		<% nav = @root_folder %>
		<% nav_list << nav %>

		<!-- collect all the nav list -->
		<% while nav.parent.present? do %>
		<% nav = nav.parent %>
		<% nav_list << nav %>
		<% end %>

		<!-- so that user wont know root id -->
		<% if @root_folder.owner_id == current_user.id %>
		<%= link_to "Home", root_path %>
		<% else %>
		<%= link_to "Shared with me", shared_path %>
		<% end %>

		<!-- reverse print  -->
		<% nav_list.reverse.each do |nav| %>
		<!-- never print root  -->
		<% if nav.name != 'root'  %>
		<!-- unclickable -->
		<% if nav_list.first == nav %>
		/ <%= nav.name %>
		<!-- clickable -->
		<% else %>
		/ <%= link_to nav.name, folder_uploads_path(nav) %> 
		<% end %>
		<% end %>
		<% end %>


	</div>

	<% if @root_folder.owner_id == current_user.id %>
	<span>
		<%= link_to new_folder_upload_path(folder_id: @root_folder.id), remote: true do %>
		<i class="fas fa-plus-square mid-icon float-right add file" data-toggle="modal" data-target="#uploads_modal"></i>
		<% end %>
	</span>

	<span>
		<%= link_to new_folder_path(parent_id: @root_folder.id), remote: true do %>
		<i class="fas fa-folder-plus mid-icon float-right mr-2 orange" data-toggle="modal" data-target="#add_folder_modal"></i>
		<% end %>
	</span>
	<% end %>
</div>

<div class="clearfix"></div>

app/views/shared/_flash_messages.html.erb
<% if notice.present? %>
<div class="alert alert-primary alert-dismissible fade show" role="alert">
	<%= notice %>
	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
		<span aria-hidden="true">&times;</span>
	</button>
</div>
<% end %>

<% if alert.present? %>
<div class="alert alert-warning alert-dismissible fade show" role="alert">
	<%= alert %>
	<button type="button" class="close" data-dismiss="alert" aria-label="Close">
		<span aria-hidden="true">&times;</span>
	</button>
</div>
<% end %>

app/views/shared/_modals.html.erb
<!-- modal begins -->
<div class="modal fade" id="add_folder_modal" role="dialog">
	<div class="modal-dialog" id="folder_form_render">

	</div>
</div>
<!-- modal end -->



<!-- modal begins -->
<div class="modal fade" id="uploads_modal" role="dialog">
	<div class="modal-dialog" id="file_form_render">

	</div>
</div>
<!-- modal end -->

app/views/shared/_navbar.html.erb
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">
  <a class="navbar-brand" href="javascript:void();">Drop Clone</a>
  <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
    <span class="navbar-toggler-icon"></span>
  </button>

  <div class="collapse navbar-collapse" id="navbarSupportedContent">
    <ul class="navbar-nav mr-auto">
      <% if user_signed_in? %>
      <li class="nav-item">
        <%= link_to "My Files", root_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Shared with me", shared_path, class: "nav-link" %>
      </li>
      <% end %>
    </ul>
    <ul class="navbar-nav float-right">
      <% if !user_signed_in? %>
      <li class="nav-item">
        <%= link_to "Log In", new_user_session_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Sign Up", new_user_registration_path, class: "nav-link" %>
      </li>
      <% else %>
      <li class="nav-item">
        <%= link_to "My Profile", edit_user_registration_path, class: "nav-link" %>
      </li>
      <li class="nav-item">
        <%= link_to "Logout", destroy_user_session_path, class: "nav-link", method: :delete %>
      </li>
      <% end %>
    </ul>
  </div>
</nav>

app/views/shares/index.html.erb
<div class="text-info col-md-12 m-2">
	<h5>Shared With me</h5>
</div>

<div class="col-md-12 row">
	<% @folders.each do |folder| %>

	<div class="text-center pl-5 folder row mb-4" >
		<div>
			<%= link_to folder_uploads_path(folder) do %>
			<i class="fas fa-folder xl-icon" title="<%= folder.name %>"></i>
			<% end %>
			<br>
			<div>
				<%= folder.name %>
			</div>
		</div>
	</div>

	<% end %>
</div>

app/views/uploads/_each.html.erb
<div>
	<div>
		<%= link_to rails_blob_path(upload, disposition: 'preview'), target: 'blank' do %>
		<i class="fas fa-file-alt xl-icon file mb-2" title="<%= upload.filename %>"></i>
		<span><%= upload.filename %></span>
		<% end %>
	</div>
</div>

<div class="col-md-6">
	<% if @root_folder.owner_id == current_user.id %>

	<%= link_to folder_upload_path(@root_folder, upload.id), remote: true, data: {confirm: 'Do you want to remove the folder?'} do %>
	<i class="zoom fas fa-share-alt xs-icon pr-2 float-left share" title="<%= upload.filename %>" data-toggle="modal" data-target="#share_modal"></i>
	<% end %>

	<%= link_to folder_upload_path(@root_folder, upload.id), remote: true, data: {confirm: 'Do you want to remove the file?'}, method: :delete do %>
	<i class="fas fa-trash-alt xs-icon  float-left delete" title="<%= upload.filename %>"></i>
	<% end %>
	<% end %>
</div>

app/views/uploads/_form.html.erb
<%= form_for [@folder, Upload.new], id: 'upload_form', remote: true do |f| %>
<div class="modal-content">
	<div class="modal-header">
		<h5 class="modal-title" id="exampleModalLabel">
			Upload Files Here
		</h5>
		<button type="button" class="close" data-dismiss="modal" aria-label="Close" id="close_file_modal">
			<span aria-hidden="true">&times;</span>
		</button>
	</div>
	<div class="modal-body">
		<div class="form-group">
			<%= f.file_field :uploads, multiple: true, class: "form-control", required: "required" %>
		</div>
	</div>
	<div class="modal-footer">
		<button type="button" class="btn btn-sm btn-secondary" data-dismiss="modal">Close</button>
		<button type="submit" class="btn btn-sm btn-primary">Save changes</button>
	</div>
</div>
<% end %>

app/views/uploads/_list.html.erb
<% if @root_folder.uploads.present? %>

<div class="text-info col-md-12 m-2">
	<h5>Uploads</h5>
</div>

<% @root_folder.uploads.each do |upload| %>
<div class="text-center pl-5 folder row mb-4" id="upload_<%= upload.id %>">
	<%= render 'uploads/each', {upload: upload} %>
</div>
<% end %>

<% end %>

app/views/uploads/create.js.erb
$("#close_file_modal").trigger("click");
$('#upload_list').html("<%= j render 'uploads/list' %>");

app/views/uploads/destroy.js.erb
$('#upload_list').html("<%= j render 'uploads/list' %>")

app/views/uploads/new.js.erb
$("#file_form_render").html("<%= j render 'uploads/form' %>");